version: '3.6'

services:
  backend:
    image: registry.gitlab.com/rgcalsaverini/iff-iat/app:${APP_VERSION:-latest}
    volumes:
      - ${IAT_HOME:-/iat}/templates:/templates
      - ${IAT_HOME:-/iat}/configs.yaml:/root/configs.yaml
      - ${IAT_HOME:-/iat}/disclaimer.md:/root/disclaimer.md
      - ${IAT_HOME:-/iat}/ssl:/ssl
    ports:
      - 80:80
      - 443:443
    networks:
      - iat_network

  mongo:
    image: mongo:3.7
    volumes:
      - /iat/db:/data/db
    networks:
      - iat_network

networks:
    iat_network:
      driver: bridge
